FROM datamove/mlcourse_ai:latest

ARG USER_ID
ARG GROUP_ID
ARG USER_NAME
ARG GROUP_NAME

RUN if ! getent group ${GROUP_ID}; \
      then groupadd -g ${GROUP_ID} ${GROUP_NAME}; fi && \
    if ! getent passwd ${USER_ID}; \
      then useradd -u ${USER_ID} -g ${GROUP_ID} -d /notebooks/home ${USER_NAME}; fi

#RUN groupadd -g ${GROUP_ID} ${USER_NAME} && \
#    useradd -u ${USER_ID} -g ${GROUP_ID} -d /notebooks/home ${USER_NAME}


#RUN if [ ${USER_ID:-0} -ne 0 ] && [ ${GROUP_ID:-0} -ne 0 ]; then \
#    useradd -u ${USER_ID} -g ${GROUP_ID} -U ${USER_NAME} -m /notebooks/home \
#;fi
        
USER ${USER_NAME}

