FROM datamove/mlcourse_ai:latest

ARG USER_ID
ARG GROUP_ID
ARG USER_NAME

RUN groupadd -g ${GROUP_ID} ${USER_NAME} && \
    useradd -u ${USER_ID} -g ${GROUP_ID} -d /notebooks/home ${USER_NAME}


#RUN if [ ${USER_ID:-0} -ne 0 ] && [ ${GROUP_ID:-0} -ne 0 ]; then \
#    useradd -u ${USER_ID} -g ${GROUP_ID} -U ${USER_NAME} -m /notebooks/home \
#;fi
        
USER ${USER_NAME}

