version: '3.2'
services:
  mlcourse:
    build:
      context: .
      dockerfile: Dockerfile-user
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - USER_NAME=${USER}
        - GROUP_NAME=${GROUP_NAME}
    volumes:
      - ${PWD}:/notebooks
    working_dir: /notebooks
    ports:
      - 4545:8888
    # environment:
    #  - HOME=/notebooks/home
    entrypoint:
     - jupyter-notebook
     - --NotebookApp.ip=0.0.0.0
     - --NotebookApp.password_required=False
     - --NotebookApp.token=''
    
