name: pre-commit

on:
  push:

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: checkout code
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2.2.2

      - name: run pre-commit action
        uses: pre-commit/action@v2.0.3

      - name: Yaspeller Action
        uses: heytitle/github-action-yaspeller@v0.0.7
        with:
          ext: "*.md"
          dir: "mlcourse_ai_jupyter_book"
